baseURL: "https://trisshav.github.io/PersonalWebsite/"
languageCode: en-us
title: trish
theme: hugo-PaperMod

enableEmoji: true
params:

  profileMode:
    enabled: true
    title: "trissha varman"
    subtitle: 'welcome! ☻'
    imageUrl: img/me.jpg
    imageWidth: 368
    imageHeight: 350

  socialIcons:
    - name: linkedin
      url: https://www.linkedin.com/in/trissha-varman-3b58401b9/
    - name: twitter
      url: 
    - name: github
      url: https://github.com/trisshaV
  
  cover:
    linkFullImages: true

  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowPostNavLinks: true

menu:
  main:
    - identifier:
      name: who?
      url: /who/
      weight: 10
      # weight is the order in which they'll appear
    - identifier: tags
      name: tags
      url: /tags/
      weight: 30
    - identifier: archives
      name: blog
      url: /archives/
      weight: 20